<a href="https://colab.research.google.com/github/YunchenHo/python_projects/blob/main/Python%20%E6%9C%9F%E8%B2%A8%E4%BA%A4%E6%98%93%E5%B0%88%E6%A1%88/Python_%E6%9C%9F%E8%B2%A8%E4%BA%A4%E6%98%93%E5%B0%88%E6%A1%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 環境設定

進入程式請先執行下面的 `! pip install Backtesting`

In [ ]:
! pip install Backtesting

Collecting Backtesting
  Using cached backtesting-0.6.5-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from Backtesting) (2.0.2)
Requirement already satisfied: pandas!=0.25.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from Backtesting) (2.2.2)
Requirement already satisfied: bokeh!=3.0.*,!=3.2.*,>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from Backtesting) (3.8.2)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->Backtesting) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->Backtesting) (1.3.3)
Requirement already satisfied: narwhals>=1.13 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->Backtesting) (2.17.0)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->Backtesting) (26.0)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->Backtesting) (11.3.0)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->Backtesting) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->Backtesting) (6.5.1)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->Backtesting) (2025.11.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas!=0.25.0,>=0.25.0->Backtesting) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=0.25.0,>=0.25.0->Backtesting) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=0.25.0,>=0.25.0->Backtesting) (2025.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2>=2.9->bokeh!=3.0.*,!=3.2.*,>=3.0.0->Backtesting) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas!=0.25.0,>=0.25.0->Backtesting) (1.17.0)
Using cached backtesting-0.6.5-py3-none-any.whl (192 kB)
Installing collected packages: Backtesting
Successfully installed Backtesting-0.6.5

In [ ]:
!pip uninstall backtesting -y

Found existing installation: backtesting 0.6.5
Uninstalling backtesting-0.6.5:
  Successfully uninstalled backtesting-0.6.5

# 主程式

In [ ]:
# 掛載自己的雲端硬碟
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from backtesting.test import SMA, GOOG
import pandas as pd

# 更換成自己檔案在雲端上的路徑
data_path = "/content/drive/MyDrive/EURUSD_M1_train.csv"

# 匯入資料
df = pd.read_csv(data_path, names=GOOG.columns)
df.index = pd.to_datetime(df.index)
df.drop(index=df.index[0], inplace=True)
df = df.astype("float")

df.head()

/tmp/ipykernel_736/3638836301.py:10: DtypeWarning: Columns (1,2,3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_path, names=GOOG.columns)

                        Open     High      Low    Close  Volume
2017-01-02 02:00:00  1.05155  1.05197  1.05155  1.05190     0.0
2017-01-02 02:01:00  1.05209  1.05209  1.05177  1.05179     0.0
2017-01-02 02:02:00  1.05177  1.05198  1.05177  1.05178     0.0
2017-01-02 02:03:00  1.05188  1.05200  1.05188  1.05200     0.0
2017-01-02 02:04:00  1.05196  1.05204  1.05196  1.05203     0.0

## 策略

請在這邊撰寫屬於自己的策略

如何下單請參考:
https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#gsc.tab=0

以下範例示範簡單的黃金交叉策略，詳細說明可參考
https://rich01.com/what-is-golden-cross/

In [ ]:
from backtesting import Strategy

class ImprovedStrategy2(Strategy): # 版本二(修正架構)
    def init(self):
        # 初始化策略
        self.i = 0
        self.count1 = 0
        self.count2 = 0
        self.lessamount = 0
        self.higher_high = 0
        self.higher_low = 0
        self.lower_high = 0
        self.lower_low = 0

    def next(self):
        # 定義策略的執行邏輯
          current_high = self.data.High[self.i]
          current_low = self.data.Low[self.i]

          if self.i < 3000000:

            self.i += 1

            if current_high > self.higher_high and current_low > self.higher_low:
                self.count1 += 1

                if self.count1 - self.count2 >= 80: # 如果連續出現更高高點和更高低點，執行賣出操作
                    sell_amount = 10000000

                    if self.lessamount >= 1 and self.lessamount < 20:  # 賣出資金
                      self.sell(size=sell_amount * self.lessamount)
                      self.lessamount = 0

                    self.higher_high = current_high
                    self.higher_low = current_low
                    self.lower_high = current_high
                    self.lower_low = current_low

                    self.count1 = 0
                    self.count2 = 0


            elif current_high < self.lower_high and current_low < self.lower_low:
                self.count2 += 1

                if self.count2 - self.count1 >= 40: # 如果連續出现更低高點和更低低點，執行買入操作
                  buy_amount = 10000000 # 買入资金
                  self.lessamount += 1

                  if self.lessamount < 10:
                    self.buy(size=buy_amount)  # 一次買入10000000元

                  self.higher_high = current_high
                  self.higher_low = current_low
                  self.lower_high = current_high
                  self.lower_low = current_low

                  self.count1 = 0
                  self.count2 = 0

In [ ]:
from backtesting import Strategy

class ImprovedStrategy3(Strategy): # 版本三(數據調整)_最終版本!
    def init(self):
        # 初始化策略
        self.i = 0
        self.count1 = 0
        self.count2 = 0
        self.lessamount = 0
        self.higher_high = 0
        self.higher_low = 0
        self.lower_high = 0
        self.lower_low = 0

    def next(self):
        # 定義策略的執行邏輯
          current_high = self.data.High[self.i]
          current_low = self.data.Low[self.i]

          if self.i < 3000000:

            self.i += 1

            if current_high > self.higher_high and current_low > self.higher_low:
                self.count1 += 1

                if self.count1 - self.count2 >= 80: # 如果連續出現更高高點和更高低點，執行賣出操作
                    sell_amount = 11000000

                    if self.lessamount >= 1 and self.lessamount <= 20:  # 賣出資金
                      self.sell(size=sell_amount * self.lessamount)
                      self.lessamount = 0

                    self.higher_high = current_high
                    self.higher_low = current_low
                    self.lower_high = current_high
                    self.lower_low = current_low

                    self.count1 = 0
                    self.count2 = 0


            elif current_high < self.lower_high and current_low < self.lower_low:
                self.count2 += 1

                if self.count2 - self.count1 >= 40: # 如果連續出现更低高點和更低低點，執行買入操作
                  buy_amount = 11100000 # 買入资金
                  self.lessamount += 1

                  if self.lessamount < 9:
                    self.buy(size=buy_amount)  # 一次買入10000000元

                  self.higher_high = current_high
                  self.higher_low = current_low
                  self.lower_high = current_high
                  self.lower_low = current_low

                  self.count1 = 0
                  self.count2 = 0

In [ ]:
# return至少要大於0
# 看夏普值評分

## 執行回測

### 設定
* 初始金額：100000000
* 手續費：0.00005

In [ ]:
bt = Backtest(df, ImprovedStrategy3,cash=100000000, commission = 0.00005, exclusive_orders=False) #SmaCross為class的變數名字，可以改變 #看要設True or False

#同個時間點同時執行多個訂單

output = bt.run()

output

/tmp/ipykernel_736/3126685105.py:1: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt = Backtest(df, ImprovedStrategy3,cash=100000000, commission = 0.00005, exclusive_orders=False) #SmaCross為class的變數名字，可以改變 #看要設True or False

Backtest.run:   0%|          | 0/2231473 [00:00<?, ?bar/s]

/tmp/ipykernel_736/3126685105.py:5: UserWarning: Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.
  output = bt.run()

Start                     2017-01-02 02:00:00
End                       2022-12-30 16:58:00
Duration                   2188 days 14:58:00
Exposure Time [%]                    99.79812
Equity Final [$]              106301983.68935
Equity Peak [$]               106310285.72805
Commissions [$]                14983048.44165
Return [%]                            6.30198
Buy & Hold Return [%]                 1.77203
Return (Ann.) [%]                     0.82402
Volatility (Ann.) [%]                 2.11925
CAGR [%]                              0.70615
Sharpe Ratio                          0.38883
Sortino Ratio                         0.52909
Calmar Ratio                           0.1704
Alpha [%]                             6.27639
Beta                                  0.01444
Max. Drawdown [%]                    -4.83576
Avg. Drawdown [%]                    -0.04081
Max. Drawdown Duration     1701 days 12:13:00
Avg. Drawdown Duration        2 days 21:23:00
# Trades                                17355
Win Rate [%]                         59.32584
Best Trade [%]                        2.42218
Worst Trade [%]                      -1.80198
Avg. Trade [%]                         0.0148
Max. Trade Duration           3 days 23:42:00
Avg. Trade Duration           0 days 09:47:00
Profit Factor                         1.21889
Expectancy [%]                        0.01509
SQN                                   2.15336
Kelly Criterion                       0.03256
_strategy                   ImprovedStrategy3
_equity_curve                             ...
_trades                              Size ...
dtype: object

### 繪製分析圖

In [ ]:
bt.plot()

/usr/local/lib/python3.12/dist-packages/backtesting/_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "

GridPlot(id='p1336', ...)